
* 2024
** 2024-04 April
*** 2024-04-11 Thursday
- 07:27    This is my first capture. Testing out the new system.
*** 2024-04-16 Tuesday
- 21:45     I'm trying to get back into journaling regularly. I don't know why I find it so difficult. This week was a bit of a rollercoaster - it's nearing the end of the semester, so all of my work is adding up and it's getting a little stressful. This is the first time that I actually feel as if I managed my time somewhat well; I have been working on projects throughout the year, and making good progress, so now that it all comes due I actually feel on top of my work. It's a good feeling. We just got our summer slate - I am going to the USCGC Resolute. I have mixed feelings about that; on the one hand, I appear to actually be going out on a deployment, which is going to be awesome. On the other, I'm literally going to the sister ship for the boat I was on my 3/c summer. I really wanted an opportunity to see some variety in the Coast Guard (and I also REALLY wanted to see the pacific northwest...) but this will be a good opportunity. I will get to see more of the operational Coast Guard than I have previously, and it will be through the lens of something somewhat familiar.
